---
- name: Installing and configuring openldap server
  hosts: centos6.localhost
  roles:
    - role-slapd
    - role-ldaputils

- name: Installing and configuring openldap client
  hosts: centos6-all
  roles:
    - role-sssd
